paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: ShengYg's Blog

baseurl: ""
url: "https://shengyg.github.io/repository"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ShengYg's Blog

description: Stylish Jekyll Theme
author:
  name: ShengYg
  email: shengy0726@gmail.com
  github: ShengYg
  twitter: holmes9412
#  pinterest: asd123
#  linkedin: asd123
  bio: Step after step the ladder is ascended.
#  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

encoding: "utf-8"
