paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
disqus: dbyll
google_analytics: dbyll
title: ShengYg's Blog
port: 3000

url: "https://shengyg.github.io"
baseurl: "/repository"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ShengYg's Blog

description: Stylish Jekyll Theme
author:
  name: ShengYg
  email: shengy0726@gmail.com
  github: ShengYg
  twitter: holmes9412
#  pinterest: asd123
  weibo: holmes_94
  bio: Step after step the ladder is ascended.
#  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


plugins: ['jekyll-paginate', 'redcarpet']

